name: frontend
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^14.0.0
  intl: ^0.19.0
  dio: ^5.4.0
  http: ^1.2.1
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  logger: ^2.0.2
  uuid: ^4.0.0
  web_socket_channel: ^2.4.0
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1 # For generating serialization code
  build_runner: ^2.4.6 # For running code generators like json_serializable

flutter:
  uses-material-design: true

  assets:
    - assets/images/
