name: repduel
description: Fitness tracker app with badges and ranks.
publish_to: "none"

version: 1.1.5+12

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Existing Dependencies ---
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.2
  go_router: ^16.2.1
  intl: ^0.20.2
  dio: ^5.4.0
  dio_web_adapter: ^2.1.1
  http: ^1.2.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.0.0
  fl_chart: ^1.0.0
  logger: ^2.0.2
  uuid: ^4.0.0
  web_socket_channel: ^3.0.3
  flutter_dotenv: ^6.0.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.1
  image_picker_for_web: ^3.0.1
  riverpod: ^2.6.1
  purchases_flutter: ^9.3.0
  flutter_stripe: ^12.0.2

  # --- NEW DEPENDENCIES FOR SHARING ---
  share_plus: ^11.1.0
  screenshot: ^3.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1 # For generating serialization code
  build_runner: ^2.4.6 # For running code generators like json_serializable

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/ranks/
    - assets/images/placeholder.png